
package wst.lab1.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "ServiceException", targetNamespace = "http://ws.lab1.wst/")
public class ServiceException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private ServiceFault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public ServiceException(String message, ServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ServiceException(String message, ServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: wst.lab1.ws.ServiceFault
     */
    public ServiceFault getFaultInfo() {
        return faultInfo;
    }

}
